FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        coreutils \
        iproute2 \
        procps \
        qemu-user-static \
    && rm -rf /var/lib/apt/lists/*

USER 65534:65534
WORKDIR /tmp
